spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_name}
    username: ${DB_username}
    password: ${DB_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
    # static configuration
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/
      cache:
        preriod: 3600
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:9090/realms/whatsapp-clone
  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  default-produces-media-type: application/json


application:
  file:
    uploads:
      media-output-path: ./uploads
server:
  compression:
    enabled: true
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json
    min-response-size: 1024